### ISSUE TITLE
Peggo does not validate ethereum addresses format

### ISSUE THREAD

**Issue by facundomedica** [umee-network/peggo#177]
TOB-UMEE-028

There are multiple code paths in the Peggo codebase where ethereum addresses are parsed with the go-ethereum's HexToAddress function (figure 28.1) which does not return an error in case of incorrect address format passed to it.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
Here's what HexToAddress is doing

```go
// Address represents the 20 byte address of an Ethereum account.
type Address [AddressLength]byte

// HexToAddress returns Address with byte values of s.
// If s is larger than len(h), s will be cropped from the left.
func HexToAddress(s string) Address { return BytesToAddress(FromHex(s)) }
```

It prepends `0` to odd-length hex input ( "ABB" -> "0ABB" )

```go
// FromHex returns the bytes represented by the hexadecimal string s.
// s may be prefixed with "0x".
func FromHex(s string) []byte {
	if has0xPrefix(s) {
		s = s[2:]
	}
	if len(s)%2 == 1 {
		s = "0" + s
	}
	return Hex2Bytes(s)
}
```

and restricts the length of its output

```go
// BytesToAddress returns Address with value b.
// If b is larger than len(h), b will be cropped from the left.
func BytesToAddress(b []byte) Address {
	var a Address
	a.SetBytes(b)
	return a
}
```

Hex2Bytes in particular ignores an error

```go
// Hex2Bytes returns the bytes represented by the hexadecimal string str.
func Hex2Bytes(str string) []byte {
	h, _ := hex.DecodeString(str)
	return h
}
```

resulting in some of the following behavior leaking through

```go
// DecodeString returns the bytes represented by the hexadecimal string s.
//
// DecodeString expects that src contains only hexadecimal
// characters and that src has even length.
// If the input is malformed, DecodeString returns
// the bytes decoded before the error.
func DecodeString(s string) ([]byte, error) {
	src := []byte(s)
	// We can use the source slice itself as the destination
	// because the decode loop increments by one and then the 'seen' byte is not used anymore.
	n, err := Decode(src, src)
	return src[:n], err
}
```

**Comment by toteki** [comment]
The question now is - are there any uses of `HexToAddress` in `peggo` that need to be modified, given the existing behavior?

At the very least, it is currently already deterministic and guaranteed to create 20 byte addresses even in the case of malformed input.

**Comment by facundomedica** [comment]
@toteki thanks for the analysis, I think that this is only needed in places where the user is doing the input. Adding a check in any other place won't do any good.

I'm checking with `ethcmn.IsHexAddress` which checks for length and if the string is a valid hex string.
