### ISSUE TITLE
FindLatestValset only looks in the last 2000 blocks

### ISSUE THREAD

**Issue by facundomedica** [umee-network/peggo#283]
## Summary of Bug

We encountered this edge case on Umeemania.
The network didn't send valset updates for a while and then because validators were running in `ValsetRelayModeMinimum`, they didn't think it was necessary to send a new valset update.

We should change this so if it doesn't find any valset update in the last 2000 blocks it sends one anyway, even tho it's not really necessary in terms of power change.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RafilxTenfen** [comment]
2000 blocks on eth or in umee? @facundomedica
