### ISSUE TITLE
feat: Make panic message show the address of the validator with empty power

### ISSUE THREAD

**Issue by brianosaurus** [umee-network/peggo#284]
## Summary

When there is a validator with empty power, have the panic message show the validator's address. This is useful for debugging.

## Problem Definition

When a node panics because of a validator empty power all we see is
```
May 14 03:43:26 alley umeed[1407250]: panic: generated invalid valset: invalid members: member 5: power: empty
```
This isn't helpful in debugging because we don't have information that specifically identifies the validator.
## Proposal

Show the address and any other identifying information for the validator in the panic message.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by facundomedica** [comment]
Closing as this was fixed with https://github.com/Gravity-Bridge/Gravity-Bridge/pull/162
