### ISSUE TITLE
Dockerfile set umee version to v3.x.x

### ISSUE THREAD

**Issue by RafilxTenfen** [umee-network/peggo#344]
## Summary

- After cosmos-sdk 046 umeed branch is merged to main and released, we should update the docker to point to v3.x.x

## Proposal

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment]
done in #415
