### ISSUE TITLE
feat: Re-check batch fees before relaying

### ISSUE THREAD

**Issue by facundomedica** [umee-network/peggo#40]
## Summary

I would like for each validator to check a batch's total fees again before relaying it (with some degree of tolerance/slippage).

## Problem Definition

Currently, we only check for fees when creating a batch and not when relaying it, this can create some undesired situations:

- A batch was profitable at the moment of requesting it but it's not profitable anymore (not very likely).
- A misconfigured validator is requesting unprofitable batches that other validators will pick up and relay at a loss.
- What some validators consider profitable others might not (this is the most likely case).

## Proposal

Adding a fee check before relaying batches would fix the issues listed above while also giving place to some interesting features. This fee check can be paired with a slippage parameter, so the batches are still relayed even if the price of the relayed asset goes down a little between the request and the relay events.

Note: this won't affect the signing of batches, a validator will sign all valid batches but won't relay unprofitable ones.

This could also enable:

- Validators can be in control of what they are going to relay.
- Opens up to some degree of competition between validators, because they'll try to request a batch and relay it before others. That is because if validator A has a minimum batch fee of $100 and validator B has a minimum batch fee of $110, validator A will be requesting and relaying batches more often than validator B because its minimum will be reached first.
- If a validator decides to do "cheap labor", it will be free to do so without compromising the other validators.

A follow-up idea: add the option to have a minimum batch fee per token. So a group could subsidize the transactions of a specific token to improve its bridging speed/cost.

----

## For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Thanks for the summary @facundomedica 👏  

Can you also provide an idea of how and where the implementation would look like? Where in Peggo are we adding this?

**Comment by facundomedica** [comment]
Yeah, sorry for the delay. This would add another `checkFeeThreshold` call inside `RelayBatches` (https://github.com/umee-network/peggo/blob/main/orchestrator/relayer/batch_relaying.go#L13). We have to analyze the implications of this and what would happen if someone is creating very cheap batches (everyone can request a batch, even non validators).
