### ISSUE TITLE
Update e2e test docker image

### ISSUE THREAD

**Issue by gsk967** [umee-network/peggo#414]
## Summary
Use releases new version of docker images from umee-network repo for e2e 

## Problem Definition
Currently we are building docker image with umeed and peggo here we are making umeed binary from base , so instead of making binary we can use released version of umeed from github or docker image binary 

## Proposal

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment]
closed by: c8b024aa8e78a5ba67767c37b24cd81006521442
