### ISSUE TITLE
Timing Configurations

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/peggo#42]
There are three timing inputs in which I'd like for us to examine if they should be externally configurable or not:

- [x] https://github.com/umee-network/peggo/blob/main/orchestrator/eth_event_watcher.go#L14-L24
- [ ] https://github.com/umee-network/peggo/blob/main/orchestrator/eth_event_watcher.go#L26
- [x] https://github.com/umee-network/peggo/blob/main/orchestrator/eth_event_watcher.go#L219

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by facundomedica** [comment]
`ethBlockConfirmationDelay` shouldn't be configurable or at least not by the operator. See: https://github.com/code-423n4/2021-08-gravitybridge-findings/issues/12 We maybe should do something like this: https://github.com/althea-net/cosmos-gravity-bridge/blob/main/orchestrator/orchestrator/src/ethereum_event_watcher.rs#L222 in which depending on the Ethereum network we are connecting to we set a different value.

Some notes: I think that changing  `defaultBlocksToSearch` along with the `--orch-loop-duration` flag might be an easy way to speed up syncing times for Peggo. I've tried `--orch-loop-duration="5s"` and got some volunteers to do the same, and peggo synced way faster that way; once synced the flag can should be removed.

**Comment by alexanderbez** [comment]
> `ethBlockConfirmationDelay` shouldn't be configurable or at least not by the operator. See: [code-423n4/2021-08-gravitybridge-findings#12](https://github.com/code-423n4/2021-08-gravitybridge-findings/issues/12) We maybe should do something like this: https://github.com/althea-net/cosmos-gravity-bridge/blob/main/orchestrator/orchestrator/src/ethereum_event_watcher.rs#L222 in which depending on the Ethereum network we are connecting to we set a different value.


ACK. Let's go with that approach 👍
