### ISSUE TITLE
Add a profit multiplier/percentage to batch relaying

### ISSUE THREAD

**Issue by facundomedica** [umee-network/peggo#57]
## Summary

Validators don't have an easy way to set how much they want to earn. They should be able to add a % of profit on top of `fees - profits`. This will provide more control over the orchestrator, add some competition, and improve incentives.

## Proposal

Add a flag like `--relayer-profit-mult` or `--relayer-profit-percentage` that receives a number. Then profitability will be calculated using that value so the batch will be profitable only if batch fees are over X% greater than gas cost. I'm not very good at math, I'll need @alexanderbez to help me define this. 

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by facundomedica** [comment]
Sure thing. I think that it should be a value passed to the `IsBatchProfitable` for simplicity (https://github.com/umee-network/peggo/blob/main/orchestrator/relayer/batch_relaying.go#L197)

**Comment by alexanderbez** [comment]
Looks like we just need to pass in a multiplier (float64) and evaluate `ceil(totalFeeInUSDDec * profitMult) > gasCostInUSDDec`

**Comment by facundomedica** [comment]
@alexanderbez agree, I'll get this done today. What would be a good default value? I think it should be something over 1.0, something like 1.1 or 1.05.

**Comment by alexanderbez** [comment]
> What would be a good default value? I think it should be something over 1.0, something like 1.1 or 1.05.

It should be `1.0`

> EDIT: It should be totalFeeInUSDDec > (profitMult * gasCostInUSDDec)

Yes, this sounds correct!
