### ISSUE TITLE
SafeMath library is not always used in Gravity

### ISSUE THREAD

**Issue by facundomedica** [umee-network/peggo#67]
This one seems to be solved on Althea and PeggyJV (at least there are mentions of SafeMath in Gravity.sol)

https://github.com/PeggyJV/gravity-bridge/blob/main/solidity/contracts/Gravity.sol#L30
https://github.com/althea-net/cosmos-gravity-bridge/blob/main/solidity/contracts/Gravity.sol#L46

Ref: https://github.com/code-423n4/2021-08-gravitybridge-findings/issues/60

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Hsiang-xxs** [comment]
I didn't find any pending issues related to this in our smart contracts

**Comment by facundomedica** [comment]
Ok, so I'm closing this one 🆗 Thanks you!
