### ISSUE TITLE
Upgrade to at least Solidity 0.8.4

### ISSUE THREAD

**Issue by facundomedica** [umee-network/peggo#68]
We are currently at ^0.8.0. Figure out if we should anchor it to a specific version.

Ref: https://github.com/code-423n4/2021-08-gravitybridge-findings/issues/45

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Hsiang-xxs** [comment]
Yep, of course. Usually it's recommended to use a specific Solidity compiler version

**Comment by facundomedica** [comment]
Should we change the pragma to be ^0.8.4?

**Comment by Hsiang-xxs** [comment]
No, it should be `0.8.4`. It still could not lock to a specific compiler version by using `^`

**Comment by alexanderbez** [comment]
Did we already address this @Hsiang-xxs? I feel like I saw this version used in a PR recently.

**Comment by Hsiang-xxs** [comment]
Yep, already fixed. Let's close this issue :)
